services:
  nodedb:
    image: mysql:latest
    container_name: nodedb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=4BSZN4Ixyu67Pbtv
      - MYSQL_DATABASE=nodedb
      - MYSQL_USER=nodeadmin
      - MYSQL_PASSWORD=Epi0h5hmwXgAMwBn
    volumes:
      - ./nodeDBData:/var/lib/mysql
    networks:
      - eventsNet

  nodeapi:
    build: .
    container_name: nodeapi
    ports:
      - "8081:8081"
    environment:
      - HOST=0.0.0.0
      - PORT=8081
      - DATABASE_URL=mysql://nodeadmin:Epi0h5hmwXgAMwBn@nodedb:3306/nodedb
    networks:
      - eventsNet
    depends_on:
      - nodedb


networks:
  eventsNet:
